# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: build

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install bump
      - run: git config --global user.email "info@easyapis.io"
      - run: git config --global user.name "Danny Veldhoen"
      - run: bump
      - run: git push https://${{secrets.GPR_TOKEN}}@github.com/dveldhoen/easyinvoice

#  publish-npm:
#    needs: bump-version
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: 'master'
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#          registry-url: https://registry.npmjs.org/
#      - run: cat package.json
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

#  publish-gpr:
#    needs: bump-version
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: 'master'
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#          registry-url: https://npm.pkg.github.com/
#          scope: '@dveldhoen'
#      - env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        run: |
#          npm config set registry 'https://npm.pkg.github.com/@dveldhoen'
#          npm publish



